# Generated by Django 5.1.2 on 2024-11-13 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='date_data',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='reviewstat',
            name='date_data',
            field=models.DateTimeField(default=None),
        ),
    ]
