# Generated by Django 5.1.2 on 2024-10-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_coursedata_course_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_courses', to='forms.coursedata')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inter_faculties', to='forms.coursedata')),
            ],
            options={
                'db_table': 'Inter',
                'unique_together': {('course_id', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_courses', to='forms.coursedata')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normal_faculties', to='forms.coursedata')),
            ],
            options={
                'db_table': 'Normal',
                'unique_together': {('course_id', 'faculty')},
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_courses', to='forms.coursedata')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_faculties', to='forms.coursedata')),
            ],
            options={
                'db_table': 'Special',
                'unique_together': {('course_id', 'faculty')},
            },
        ),
    ]
