# Generated by Django 5.1.2 on 2024-11-25 04:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_qa_answer_posted_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qa_answer',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 4, 14, 59, 159329, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='qa_question',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 4, 14, 59, 154328, tzinfo=datetime.timezone.utc)),
        ),
    ]
