# Generated by Django 5.1.2 on 2024-10-21 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_coursedata_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewstat',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='faculty',
        ),
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('review', 'user')},
        ),
        migrations.CreateModel(
            name='Inter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inter_courses', to='forms.coursedata')),
            ],
            options={
                'db_table': 'Inter',
            },
        ),
        migrations.CreateModel(
            name='Normal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='normal_courses', to='forms.coursedata')),
            ],
            options={
                'db_table': 'Normal',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='special_courses', to='forms.coursedata')),
            ],
            options={
                'db_table': 'Special',
            },
        ),
        migrations.RemoveField(
            model_name='summary',
            name='faculty',
        ),
    ]
