# Generated by Django 5.1.2 on 2024-11-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_history_anonymous_note_pen_name_alter_bookmark_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(default=None, max_length=255, upload_to='note_files/'),
        ),
    ]
