# Generated by Django 5.1.2 on 2024-11-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_qa_answer_posted_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviewstat',
            name='date_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
