# Generated by Django 5.1.2 on 2024-11-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_history_anonymous_note_pen_name_alter_bookmark_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='anonymous',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
