# Generated by Django 5.1.2 on 2024-11-25 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_note_date_data_alter_reviewstat_date_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa_question',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='forms.coursedata'),
        ),
    ]
