# Generated by Django 5.1.2 on 2024-11-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_note_note_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
