# Generated by Django 5.1.2 on 2024-10-25 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_review_id_bookmark_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewstat',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='academic_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='pen_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='course_id',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='course_name',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='course_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='coursedata',
            name='faculty',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='reviews',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='qa',
            name='comment',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='reviewstat',
            name='date_data',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='reviewstat',
            name='grade',
            field=models.CharField(default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='reviewstat',
            name='review',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='forms.coursereview'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='sum_text',
            field=models.TextField(default=None),
        ),
    ]
