# Generated by Django 5.1.2 on 2024-10-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_inter_normal_special'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursedata',
            name='course_type',
        ),
    ]
