# Generated by Django 5.1.2 on 2024-11-25 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_alter_note_date_data_alter_reviewstat_date_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_file',
        ),
        migrations.AddField(
            model_name='note',
            name='pdf_url',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
