# Generated by Django 5.1.2 on 2024-11-29 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_qa_question_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa_question',
            name='question_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qa_question',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.coursedata'),
        ),
    ]
