# Generated by Django 5.1.2 on 2024-10-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_reviewstat_upvotes_reviewstat_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedata',
            unique_together={('course_id', 'faculty', 'course_type')},
        ),
    ]
