# Generated by Django 5.1.2 on 2024-11-19 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_remove_history_anonymous_coursereview_anonymous_and_more'),
        ('forms', '0004_note_file_name'),
    ]

    operations = [
    ]
