# Generated by Django 5.1.2 on 2024-11-30 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_note_note_file_note_pdf_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_id', models.CharField(default=None, max_length=100, null=True)),
                ('img_link', models.TextField(default=None, null=True)),
                ('img_delete_hash', models.CharField(default=None, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='forms.userdata')),
            ],
            options={
                'db_table': 'UserProfile',
            },
        ),
    ]
