# Generated by Django 5.1.2 on 2024-11-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_merge_20241119_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
