# Generated by Django 5.1.2 on 2024-10-30 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_coursedata_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewstat',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='userdata',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='userdata',
            name='profile_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_name',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_type',
            field=models.CharField(default='student', max_length=20),
        ),
        migrations.CreateModel(
            name='FollowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='forms.userdata')),
                ('this_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='forms.userdata')),
            ],
            options={
                'db_table': 'FollowData',
                'unique_together': {('this_user', 'follow_by')},
            },
        ),
        migrations.CreateModel(
            name='UpvoteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.reviewstat')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userdata')),
            ],
            options={
                'db_table': 'UpvoteStat',
                'unique_together': {('review_stat', 'user')},
            },
        ),
    ]
