# Generated by Django 5.1.2 on 2024-10-20 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_coursedata_course_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='qa',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='reviewstat',
            old_name='review_id',
            new_name='review',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='summary',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='inter',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='normal',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='special',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursereview',
            name='faculty',
        ),
        migrations.AlterUniqueTogether(
            name='summary',
            unique_together={('course', 'user')},
        ),
        migrations.AddField(
            model_name='inter',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inter_courses', to='forms.coursedata'),
        ),
        migrations.AddField(
            model_name='normal',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='normal_courses', to='forms.coursedata'),
        ),
        migrations.AddField(
            model_name='special',
            name='course',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='special_courses', to='forms.coursedata'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('review', 'user')},
        ),
        migrations.RemoveField(
            model_name='inter',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='inter',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='normal',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='normal',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='special',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='special',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='faculty',
        ),
    ]
