# Generated by Django 5.1.2 on 2024-11-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_remove_note_note_file_note_pdf_url'),
        ('forms', '0005_qa_question_question_title_alter_qa_question_course'),
    ]

    operations = [
    ]
