# Generated by Django 5.1.2 on 2024-11-03 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_remove_reviewstat_up_votes_userdata_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa',
            old_name='comment',
            new_name='question_text',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='instructor',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default=None, max_length=255)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.qa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userdata')),
            ],
            options={
                'db_table': 'Comment',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_file', models.FileField(blank=True, null=True, upload_to='summaries/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='forms.coursedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userdata')),
            ],
            options={
                'db_table': 'Note',
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
