# Generated by Django 5.1.2 on 2024-11-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_history_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='note_file',
        ),
        migrations.AddField(
            model_name='note',
            name='pdf_url',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
