# Generated by Django 5.1.2 on 2024-11-02 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0006_remove_reviewstat_up_votes_userdata_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='comment',
        ),
        migrations.AddField(
            model_name='qa',
            name='question_text',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='userdata',
            name='instructor',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default=None)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.qa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userdata')),
            ],
            options={
                'db_table': 'Comment',
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_file', models.FileField(blank=True, null=True, upload_to='summaries/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summaries', to='forms.coursedata')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userdata')),
            ],
            options={
                'db_table': 'note',
                'unique_together': {('course', 'user')},
            },
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
    ]
