# Generated by Django 5.1.2 on 2024-12-01 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_userprofile'),
        ('forms', '0006_merge_20241130_1810'),
    ]

    operations = [
    ]
