# Generated by Django 5.1.2 on 2024-11-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_remove_qa_comment_qa_question_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='instructor',
        ),
        migrations.AddField(
            model_name='coursereview',
            name='instructor',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
