# Generated by Django 5.1.2 on 2024-11-03 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_rename_comment_qa_question_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='instructor',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
