# Generated by Django 5.1.2 on 2024-11-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('forms', '0008_alter_coursereview_instructor'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('content_type', 'object_id', 'user')},
        ),
        migrations.AddField(
            model_name='bookmark',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='data_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='attendance',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='class_type',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='effort',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='reviewstat',
            name='scoring_criteria',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(default=None, upload_to='note_files/'),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='review',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(default=None)),
                ('data_type', models.CharField(default=None, max_length=20)),
                ('content_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forms.userdata')),
            ],
            options={
                'db_table': 'History',
                'unique_together': {('content_type', 'object_id', 'user')},
            },
        ),
    ]
