# Generated by Django 5.1.2 on 2024-11-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0008_alter_coursereview_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qa',
            name='user',
        ),
        migrations.AlterField(
            model_name='note',
            name='note_file',
            field=models.FileField(default=None, upload_to='note_files/'),
        ),
        migrations.CreateModel(
            name='QA_Question',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('question_text', models.TextField(default=None)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userdata')),
            ],
            options={
                'db_table': 'QAQuestion',
            },
        ),
        migrations.CreateModel(
            name='QA_Answer',
            fields=[
                ('answer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('answer_text', models.CharField(default=None, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.userdata')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.qa_question')),
            ],
            options={
                'db_table': 'QAAnswer',
            },
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='QA',
        ),
    ]
