# Generated by Django 5.1.2 on 2024-11-12 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_remove_qa_user_alter_note_note_file_qa_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qa_answer',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qa_question',
            name='posted_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
