# Generated by Django 5.1.2 on 2024-11-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0009_alter_bookmark_unique_together_bookmark_content_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursedata',
            unique_together={('course_id', 'course_type')},
        ),
        migrations.AddField(
            model_name='coursereview',
            name='faculty',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='faculty',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='qa',
            name='faculty',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.RemoveField(
            model_name='coursedata',
            name='faculty',
        ),
    ]
