# Generated by Django 5.1.2 on 2024-11-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0011_qa_answer_upvote_qa_question_upvote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qa_answer_upvote',
            old_name='qa',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='qa_question_upvote',
            old_name='qa',
            new_name='question',
        ),
        migrations.AlterUniqueTogether(
            name='qa_answer_upvote',
            unique_together={('answer', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='qa_question_upvote',
            unique_together={('question', 'user')},
        ),
    ]
