# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0  # Specify the MySQL version you need
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: github_ci_test
          MYSQL_USER: django
          MYSQL_PASSWORD: django_password
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        pip install coverage
    - name: Grant Permissions for Testing
      env:
        MYSQL_PWD: root
      run: |
        mysql -u root -h 172.18.0.1 -e "GRANT ALL PRIVILEGES ON test_github_ci_test.* TO 'django'@'%'; FLUSH PRIVILEGES;"
    - name: Set up database
      env:
        MYSQL_HOST: 172.18.0.1
        MYSQL_PORT: 3306
        MYSQLDATABASE: github_ci_test
        MYSQLUSER: django
        MYSQLPASS: django_password
      run: |
        python backend/manage.py migrate
    - name: Set Environments
      run: |
        echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
        echo DEBUG=${{ secrets.DEBUG }} >> .env
        echo TIME_ZONE=${{ secrets.TIME_ZONE }} >> .env
        echo DJANGO_API_ENDPOINT=${{ secrets.DJANGO_API_ENDPOINT }} >> .env
        echo MYSQLHOST=172.18.0.1 >> .env
        echo MYSQLUSER=django >> .env
        echo MYSQLPASS=django_password >> .env
        echo MYSQLDATABASE=github_ci_test >> .env
        echo MYSQLPORT=3306 >> .env
    - name: Test with coverage
      run: |
        cd backend
        coverage run manage.py test
    - name: Generate Coverage Report
      run: |
        cd backend
        coverage report
        coverage html