# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        cd backend
        pip install -r requirements.txt
        pip install coverage
    - name: Set Environments
      run: |
        echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
        echo DEBUG=${{ secrets.DEBUG }} >> .env
        echo TIME_ZONE=${{ secrets.TIME_ZONE }} >> .env
        echo DJANGO_API_ENDPOINT=${{ secrets.DJANGO_API_ENDPOINT }} >> .env
        echo MYSQLHOST=${{ secrets.MYSQLHOST }} >> .env
        echo MYSQLUSER=${{ secrets.MYSQLUSER }} >> .env
        echo MYSQLPASS=${{ secrets.MYSQLPASS }} >> .env
        echo MYSQLDATABASE=${{ secrets.MYSQLDATABASE }} >> .env
    - name: Test with coverage
      run: |
        cd backend
        coverage run manage.py test
    - name: Generate Coverage Report
      run: |
        coverage report