name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Set Environments
      run: |
        echo SECRET_KEY="${{ secrets.SECRET_KEY }}" >> .env
        echo DEBUG=${{ secrets.DEBUG }} >> .env
        echo TIME_ZONE=${{ secrets.TIME_ZONE }} >> .env
        echo ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} >> .env
    - name: Run Tests
      run: |
        cd backend
        python manage.py test
