# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Flake8

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
    - name: Lint with flake8
      run: |
        cd backend
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --extend-exclude=manage.py,kuvein/,*/__init__.py,*/admin.py,*/tests.py,*/views.py,*/migrations/,venv/
      continue-on-error: true